# Generated by Django 5.2.8 on 2026-06-27 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(choices=[('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ("Qo'ng'iroq", "Qo'ng'iroq"), ('Veb-sayt', 'Veb-sayt'), ('Tavsiya', 'Tavsiya'), ('Boshqa', 'Boshqa')], default='Boshqa', max_length=50)),
                ('board', models.CharField(choices=[('sales', 'Sales'), ('cold', 'Cold')], default='sales', max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('sub_status', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created', 'Created'), ('status', 'Status changed'), ('sub_status', 'Sub-status changed'), ('comment', 'Comment'), ('call', 'Call'), ('transfer', 'Transfer'), ('meeting', 'Meeting')], max_length=20)),
                ('from_value', models.CharField(blank=True, max_length=200, null=True)),
                ('to_value', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('meeting_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_type', models.CharField(blank=True, choices=[('Ofisda', 'Ofisda'), ('Showroomda', 'Showroomda'), ('Online', 'Online'), ('Obyektda', 'Obyektda')], max_length=20, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_lead_events', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leads.lead')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['board', 'status'], name='leads_lead_board_a8ccd7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner'], name='leads_lead_owner_i_66e55a_idx'),
        ),
    ]
