# Generated by Django 5.2.8 on 2026-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meeting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
