# Generated by Django 5.2.8 on 2026-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_subsidiya_leadevent_subsidiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ("Qo'ng'iroq", "Qo'ng'iroq"), ('Veb-sayt', 'Veb-sayt'), ('Tavsiya', 'Tavsiya'), ('Reklama', 'Reklama'), ('Boshqa', 'Boshqa')], default='Boshqa', max_length=50),
        ),
        migrations.AlterField(
            model_name='leadevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('status', 'Status changed'), ('sub_status', 'Sub-status changed'), ('comment', 'Comment'), ('call', 'Call'), ('transfer', 'Transfer'), ('meeting', 'Meeting'), ('subsidiya', 'Subsidiya changed')], max_length=20),
        ),
    ]
