# Generated by Django 5.2.8 on 2026-06-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadnotification',
            name='is_read',
        ),
    ]
