# Generated by Django 5.2.8 on 2026-07-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organization',
        ),
    ]
