# Generated by Django 5.2.8 on 2026-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_lead_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
