# Generated by Django 5.2.8 on 2026-03-30 11:53

import django.core.validators
from django.db import migrations, models

from core.services.image_service import check_image_size


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0003_alter_projects_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[
                django.core.validators.FileExtensionValidator(
                    allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP',
                                        'heic', 'heif']), check_image_size]),
        ),
    ]
