# Generated by Django 5.2.8 on 2026-03-30 04:25

import django.core.validators
from django.db import migrations, models

from core.services.image_service import check_image_size


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0004_alter_projects_options_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='image',
            field=models.FileField(default=1, upload_to='projects/', validators=[
                django.core.validators.FileExtensionValidator(
                    allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'heic', 'heif']), check_image_size]),
            preserve_default=False,
        ),
    ]
