# Generated by Django 5.2.8 on 2026-03-31 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_blocks_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basement',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.AddField(
            model_name='blocks',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='projects.projects'),
        ),
        migrations.AlterField(
            model_name='floors',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
