# Generated by Django 5.2.8 on 2026-03-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks_number', models.IntegerField(default=0)),
                ('path', models.CharField(max_length=500)),
                ('navigate_to', models.CharField(max_length=200)),
                ('hover_color', models.CharField(max_length=200)),
                ('default_color', models.CharField(max_length=200)),
                ('blocks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showrooms', to='projects.blocks')),
            ],
        ),
    ]
