# Generated by Django 5.2.8 on 2026-07-02 05:39

import common.services.image_service
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.FileField(upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif']), common.services.image_service.check_image_size]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif']), common.services.image_service.check_image_size]),
        ),
    ]
