# Generated by Django 5.2.8 on 2026-07-08 09:14

import common.services.image_service
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_showroom_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Showroom 3D',
            },
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='image',
        ),
        migrations.CreateModel(
            name='ShowroomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='showroom_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif']), common.services.image_service.check_image_size])),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.showroom3d')),
            ],
        ),
    ]
