# Generated by Django 5.2.8 on 2026-07-09 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_showroom3d_remove_showroom_image_showroomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomimage',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.showroom'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Showroom3D',
        ),
    ]
