# Generated by Django 5.2.8 on 2026-07-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_showroom_height_remove_showroom_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
