# Generated by Django 5.2.8 on 2026-08-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_block_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='path',
            field=models.CharField(max_length=2000),
        ),
    ]
