# Generated by Django 5.2.8 on 2026-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
