# Generated by Django 5.2.8 on 2026-03-25 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='client.client'),
            preserve_default=False,
        ),
    ]
