# Generated by Django 5.2.8 on 2026-04-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_company_booking_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cash_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
