# Generated by Django 5.2.8 on 2026-04-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_cash_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='down_payment',
            field=models.IntegerField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%')], null=True),
        ),
    ]
