# Generated by Django 5.2.8 on 2026-06-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_booking_no_booking_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_who',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
