# Generated by Django 5.2.8 on 2026-06-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_from_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='from_who',
        ),
    ]
