# Generated by Django 5.2.8 on 2026-07-01 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_payment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
