# Generated by Django 5.2.8 on 2026-07-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_booking_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='organization',
        ),
    ]
