# Generated by Django 5.2.8 on 2026-07-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_alter_payment_created_at_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cash_payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='down_payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_term',
        ),
        migrations.AddField(
            model_name='booking',
            name='annual_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='credit_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='firm_covers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='firm_markup_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gov_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guarantee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='monthly_full',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='monthly_stage1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bosh_tolovli', 'Bosh to`lovli'), ('bosh_tolovsiz', 'Bosh to`lovsiz')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rounding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='state_threshold_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='subsidy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='subsidy_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
