# Generated by Django 5.2.8 on 2026-07-20 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_booking_status'),
        ('client', '0008_client_birth_date_client_jshshir_client_short_name'),
        ('home', '0021_backfill_home_organization'),
        ('organization', '0002_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='home.home'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('home',), name='unique_active_booking_per_home'),
        ),
    ]
