# Generated by Django 5.2.8 on 2026-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_booking_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='monthly_payment_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ownership_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='registration_workdays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
