# Generated by Django 5.2.8 on 2026-07-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_company_bank_company_director_name_and_more'),
        ('organization', '0002_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='organization.organization'),
        ),
    ]
