# Generated by Django 5.2.8 on 2026-08-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_booking_paxtazor_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='credit_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
