# Generated by Django 5.2.8 on 2026-08-17 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_alter_booking_credit_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField()),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_adjustments', to='booking.booking')),
            ],
            options={
                'ordering': ['no'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'no'), name='unique_adjustment_per_installment')],
            },
        ),
    ]
