# Generated by Django 5.2.8 on 2026-03-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
        migrations.AddField(
            model_name='home',
            name='home_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='rooms',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], db_index=True, default=1, max_length=10),
        ),
    ]
