# Generated by Django 5.2.8 on 2026-03-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_home_title_home_home_number_alter_home_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('kalit_topshirildi', 'Kalit Topshirildi'), ('nomiga_otkazib_berildi', 'Nomiga O`tkazib Berildi')], db_index=True, default='available', max_length=30),
        ),
    ]
