# Generated by Django 5.2.8 on 2026-03-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homestatushistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='basement',
        ),
    ]
