# Generated by Django 5.2.8 on 2026-03-31 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_floorplan_image'),
        ('projects', '0008_delete_basement_delete_rooms_blocks_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='blocks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homes', to='projects.blocks'),
        ),
        migrations.AlterField(
            model_name='home',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.floors'),
        ),
        migrations.AlterField(
            model_name='home',
            name='renovation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.renovation'),
        ),
    ]
