# Generated by Django 5.2.8 on 2026-03-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_home_blocks_alter_home_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan', to='home.home'),
        ),
    ]
