# Generated by Django 5.2.8 on 2026-07-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_home_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='organization',
        ),
    ]
