# Generated by Django 5.2.8 on 2026-07-02 05:39

import common.services.image_service
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_home_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(upload_to='floor_plan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif']), common.services.image_service.check_image_size]),
        ),
    ]
