# Generated by Django 5.2.8 on 2026-07-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('tasks', '0012_remove_card_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.organization'),
        ),
    ]
