# Generated by Django 5.2.8 on 2026-07-01 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calldate', models.DateTimeField(db_index=True)),
                ('clid', models.CharField(blank=True, max_length=255, null=True)),
                ('src', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('dst', models.CharField(blank=True, max_length=50, null=True)),
                ('dcontext', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('dstchannel', models.CharField(blank=True, max_length=255, null=True)),
                ('lastapp', models.CharField(blank=True, max_length=100, null=True)),
                ('lastdata', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('billsec', models.IntegerField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('amaflags', models.IntegerField(blank=True, null=True)),
                ('accountcode', models.CharField(blank=True, max_length=100, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('userfield', models.TextField(blank=True, null=True)),
                ('recordingfile', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('cnum', models.CharField(blank=True, max_length=50, null=True)),
                ('cnam', models.CharField(blank=True, max_length=100, null=True)),
                ('outbound_cnum', models.CharField(blank=True, max_length=50, null=True)),
                ('outbound_cnam', models.CharField(blank=True, max_length=100, null=True)),
                ('dst_cnam', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.CharField(blank=True, max_length=50, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='call_records/')),
                ('audio_downloaded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Detail Record',
                'verbose_name_plural': 'Call Detail Records',
                'ordering': ['-calldate'],
            },
        ),
    ]
