# Generated by Django 5.2.8 on 2026-07-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_center', '0002_callrecord_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='organization',
        ),
    ]
