# Generated by Django 5.2.8 on 2026-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('s', 'SELLER'), ('sa', 'SUPERADMIN'), ('a', 'ADMIN')], default='s', max_length=10),
        ),
    ]
