# Generated by Django 5.2.8 on 2026-06-30 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_full_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='request_log_user_id_26b09e_idx'), models.Index(fields=['created_at'], name='request_log_created_4f2782_idx'), models.Index(fields=['method'], name='request_log_method_9e699f_idx'), models.Index(fields=['status_code'], name='request_log_status__5a9c0b_idx')],
            },
        ),
    ]
