# Generated by Django 5.2.8 on 2026-03-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_delete_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='basement',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basements', to='utils.blocks'),
        ),
    ]
