# Generated by Django 5.2.8 on 2026-03-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_basement_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basement',
        ),
    ]
